"""Add email rate limiting

Revision ID: 074de02aef60
Revises: c66462688b68
Create Date: 2026-07-20 11:10:24.704002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '074de02aef60'
down_revision: Union[str, Sequence[str], None] = 'c66462688b68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_verification_email_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('verification_email_send_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verification_email_send_count')
    op.drop_column('users', 'last_verification_email_sent_at')
    # ### end Alembic commands ###
