"""add_phone_to_company

Revision ID: 0db0300414c3
Revises: bfb9312f5049
Create Date: 2026-08-09 18:49:57.968874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0db0300414c3'
down_revision: Union[str, Sequence[str], None] = 'bfb9312f5049'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'phone')
    # ### end Alembic commands ###
