"""Add performance indexes

Revision ID: 12a90941c464
Revises: e3cf4ba1cc9e
Create Date: 2026-07-16 16:50:01.691255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12a90941c464'
down_revision: Union[str, Sequence[str], None] = 'e3cf4ba1cc9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_companies_created_at'), 'companies', ['created_at'], unique=False)
    op.create_index(op.f('ix_companies_updated_at'), 'companies', ['updated_at'], unique=False)
    op.create_index(op.f('ix_customers_created_at'), 'customers', ['created_at'], unique=False)
    op.create_index(op.f('ix_customers_updated_at'), 'customers', ['updated_at'], unique=False)
    op.create_index(op.f('ix_documents_created_at'), 'documents', ['created_at'], unique=False)
    op.create_index(op.f('ix_documents_updated_at'), 'documents', ['updated_at'], unique=False)
    op.create_index(op.f('ix_drivers_availability_status'), 'drivers', ['availability_status'], unique=False)
    op.create_index(op.f('ix_drivers_created_at'), 'drivers', ['created_at'], unique=False)
    op.create_index(op.f('ix_drivers_updated_at'), 'drivers', ['updated_at'], unique=False)
    op.create_index(op.f('ix_expenses_created_at'), 'expenses', ['created_at'], unique=False)
    op.create_index(op.f('ix_expenses_updated_at'), 'expenses', ['updated_at'], unique=False)
    op.create_index(op.f('ix_orders_created_at'), 'orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_orders_order_status'), 'orders', ['order_status'], unique=False)
    op.create_index(op.f('ix_orders_updated_at'), 'orders', ['updated_at'], unique=False)
    op.create_index(op.f('ix_trips_created_at'), 'trips', ['created_at'], unique=False)
    op.create_index(op.f('ix_trips_trip_status'), 'trips', ['trip_status'], unique=False)
    op.create_index(op.f('ix_trips_updated_at'), 'trips', ['updated_at'], unique=False)
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_updated_at'), 'users', ['updated_at'], unique=False)
    op.create_index(op.f('ix_vehicles_availability_status'), 'vehicles', ['availability_status'], unique=False)
    op.create_index(op.f('ix_vehicles_created_at'), 'vehicles', ['created_at'], unique=False)
    op.create_index(op.f('ix_vehicles_updated_at'), 'vehicles', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicles_updated_at'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_created_at'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_availability_status'), table_name='vehicles')
    op.drop_index(op.f('ix_users_updated_at'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_index(op.f('ix_trips_updated_at'), table_name='trips')
    op.drop_index(op.f('ix_trips_trip_status'), table_name='trips')
    op.drop_index(op.f('ix_trips_created_at'), table_name='trips')
    op.drop_index(op.f('ix_orders_updated_at'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_created_at'), table_name='orders')
    op.drop_index(op.f('ix_expenses_updated_at'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_created_at'), table_name='expenses')
    op.drop_index(op.f('ix_drivers_updated_at'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_created_at'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_availability_status'), table_name='drivers')
    op.drop_index(op.f('ix_documents_updated_at'), table_name='documents')
    op.drop_index(op.f('ix_documents_created_at'), table_name='documents')
    op.drop_index(op.f('ix_customers_updated_at'), table_name='customers')
    op.drop_index(op.f('ix_customers_created_at'), table_name='customers')
    op.drop_index(op.f('ix_companies_updated_at'), table_name='companies')
    op.drop_index(op.f('ix_companies_created_at'), table_name='companies')
    # ### end Alembic commands ###
