"""Add logistics workflow

Revision ID: 1c14bf181c0e
Revises: 1821dc00bbd6
Create Date: 2026-07-15 15:55:04.617496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c14bf181c0e'
down_revision: Union[str, Sequence[str], None] = '1821dc00bbd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('user_id', sa.String(), nullable=True))
    op.add_column('drivers', sa.Column('availability_status', sa.String(), nullable=False))
    op.add_column('drivers', sa.Column('current_trip_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_drivers_user_id'), 'drivers', ['user_id'], unique=False)
    op.create_foreign_key(None, 'drivers', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'drivers', 'trips', ['current_trip_id'], ['id'])
    op.drop_column('drivers', 'status')
    op.add_column('orders', sa.Column('assigned_driver_id', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('assigned_vehicle_id', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('order_status', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('pickup_location', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('delivery_location', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('expected_delivery_date', sa.DateTime(timezone=True), nullable=True))
    op.drop_index(op.f('ix_orders_driver_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_vehicle_id'), table_name='orders')
    op.create_index(op.f('ix_orders_assigned_driver_id'), 'orders', ['assigned_driver_id'], unique=False)
    op.create_index(op.f('ix_orders_assigned_vehicle_id'), 'orders', ['assigned_vehicle_id'], unique=False)
    op.drop_constraint(op.f('orders_driver_id_fkey'), 'orders', type_='foreignkey')
    op.drop_constraint(op.f('orders_vehicle_id_fkey'), 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'vehicles', ['assigned_vehicle_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'drivers', ['assigned_driver_id'], ['id'])
    op.drop_column('orders', 'delivery_date')
    op.drop_column('orders', 'vehicle_id')
    op.drop_column('orders', 'destination')
    op.drop_column('orders', 'driver_id')
    op.drop_column('orders', 'pickup')
    op.drop_column('orders', 'status')
    op.add_column('trips', sa.Column('trip_status', sa.String(), nullable=False))
    op.add_column('trips', sa.Column('start_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('trips', sa.Column('end_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('trips', sa.Column('current_location', sa.String(), nullable=True))
    op.add_column('trips', sa.Column('distance_travelled', sa.Float(), nullable=True))
    op.add_column('trips', sa.Column('delivery_notes', sa.String(), nullable=True))
    op.drop_column('trips', 'start_date')
    op.drop_column('trips', 'status')
    op.drop_column('trips', 'end_date')
    op.add_column('vehicles', sa.Column('availability_status', sa.String(), nullable=False))
    op.add_column('vehicles', sa.Column('current_trip_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'vehicles', 'trips', ['current_trip_id'], ['id'])
    op.drop_column('vehicles', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'vehicles', type_='foreignkey')
    op.drop_column('vehicles', 'current_trip_id')
    op.drop_column('vehicles', 'availability_status')
    op.add_column('trips', sa.Column('end_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('trips', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('trips', sa.Column('start_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('trips', 'delivery_notes')
    op.drop_column('trips', 'distance_travelled')
    op.drop_column('trips', 'current_location')
    op.drop_column('trips', 'end_time')
    op.drop_column('trips', 'start_time')
    op.drop_column('trips', 'trip_status')
    op.add_column('orders', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('pickup', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('driver_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('destination', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('vehicle_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('delivery_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key(op.f('orders_vehicle_id_fkey'), 'orders', 'vehicles', ['vehicle_id'], ['id'])
    op.create_foreign_key(op.f('orders_driver_id_fkey'), 'orders', 'drivers', ['driver_id'], ['id'])
    op.drop_index(op.f('ix_orders_assigned_vehicle_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_assigned_driver_id'), table_name='orders')
    op.create_index(op.f('ix_orders_vehicle_id'), 'orders', ['vehicle_id'], unique=False)
    op.create_index(op.f('ix_orders_driver_id'), 'orders', ['driver_id'], unique=False)
    op.drop_column('orders', 'expected_delivery_date')
    op.drop_column('orders', 'delivery_location')
    op.drop_column('orders', 'pickup_location')
    op.drop_column('orders', 'assigned_at')
    op.drop_column('orders', 'order_status')
    op.drop_column('orders', 'assigned_vehicle_id')
    op.drop_column('orders', 'assigned_driver_id')
    op.add_column('drivers', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'drivers', type_='foreignkey')
    op.drop_constraint(None, 'drivers', type_='foreignkey')
    op.drop_index(op.f('ix_drivers_user_id'), table_name='drivers')
    op.drop_column('drivers', 'current_trip_id')
    op.drop_column('drivers', 'availability_status')
    op.drop_column('drivers', 'user_id')
    # ### end Alembic commands ###
