"""Add Driver Lifecycle Fields

Revision ID: 97152d650171
Revises: b5500fea6e05
Create Date: 2026-07-20 12:14:39.228230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97152d650171'
down_revision: Union[str, Sequence[str], None] = 'b5500fea6e05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('lifecycle_status', sa.String(), server_default='pending', nullable=False))
    op.add_column('drivers', sa.Column('terminated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('drivers', sa.Column('terminated_by', sa.String(), nullable=True))
    op.add_column('drivers', sa.Column('termination_reason', sa.String(), nullable=True))
    op.create_index(op.f('ix_drivers_lifecycle_status'), 'drivers', ['lifecycle_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_drivers_lifecycle_status'), table_name='drivers')
    op.drop_column('drivers', 'termination_reason')
    op.drop_column('drivers', 'terminated_by')
    op.drop_column('drivers', 'terminated_at')
    op.drop_column('drivers', 'lifecycle_status')
    # ### end Alembic commands ###
