"""Add password reset fields

Revision ID: b5500fea6e05
Revises: 074de02aef60
Create Date: 2026-07-20 11:21:10.545157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5500fea6e05'
down_revision: Union[str, Sequence[str], None] = '074de02aef60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reset_password_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('reset_password_token_expires', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('last_reset_password_email_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('reset_password_email_send_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reset_password_email_send_count')
    op.drop_column('users', 'last_reset_password_email_sent_at')
    op.drop_column('users', 'reset_password_token_expires')
    op.drop_column('users', 'reset_password_token')
    # ### end Alembic commands ###
