"""unified expense and drop fuel

Revision ID: b5722db512bc
Revises: c5d17df38b57
Create Date: 2026-07-16 14:36:36.888275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b5722db512bc'
down_revision: Union[str, Sequence[str], None] = 'c5d17df38b57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fuel_entries_company_id'), table_name='fuel_entries')
    op.drop_index(op.f('ix_fuel_entries_driver_id'), table_name='fuel_entries')
    op.drop_index(op.f('ix_fuel_entries_id'), table_name='fuel_entries')
    op.drop_index(op.f('ix_fuel_entries_trip_id'), table_name='fuel_entries')
    # Migrate existing fuel entries to expenses
    op.execute("""
        INSERT INTO expenses (id, trip_id, amount, category, description, date, receipt_url, created_at, updated_at)
        SELECT id, trip_id, amount, 'Fuel', notes, date, receipt_url, created_at, updated_at 
        FROM fuel_entries 
        WHERE trip_id IS NOT NULL
    """)
    op.drop_table('fuel_entries')
    op.alter_column('expenses', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('expenses', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.create_table('fuel_entries',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('driver_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('trip_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('station', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('receipt_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fuel_entries_company_id_fkey')),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], name=op.f('fuel_entries_driver_id_fkey')),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('fuel_entries_trip_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('fuel_entries_pkey'))
    )
    op.create_index(op.f('ix_fuel_entries_trip_id'), 'fuel_entries', ['trip_id'], unique=False)
    op.create_index(op.f('ix_fuel_entries_id'), 'fuel_entries', ['id'], unique=False)
    op.create_index(op.f('ix_fuel_entries_driver_id'), 'fuel_entries', ['driver_id'], unique=False)
    op.create_index(op.f('ix_fuel_entries_company_id'), 'fuel_entries', ['company_id'], unique=False)
    # ### end Alembic commands ###
