"""phase_4_1_trip_cost_tracking

Revision ID: c5d17df38b57
Revises: 7571155feb89
Create Date: 2026-07-16 14:11:56.413215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5d17df38b57'
down_revision: Union[str, Sequence[str], None] = '7571155feb89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('expenses', sa.Column('date', sa.DateTime(), server_default=sa.func.now(), nullable=False))
    op.add_column('expenses', sa.Column('receipt_url', sa.String(), nullable=True))
    op.execute("UPDATE expenses SET category = 'Other' WHERE category IS NULL")
    op.alter_column('expenses', 'category',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('fuel_entries', 'odometer')
    op.add_column('trips', sa.Column('total_cost', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('trips', sa.Column('revenue', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('trips', sa.Column('net_profit', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('trips', sa.Column('profit_margin', sa.Float(), server_default='0.0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'profit_margin')
    op.drop_column('trips', 'net_profit')
    op.drop_column('trips', 'revenue')
    op.drop_column('trips', 'total_cost')
    op.add_column('fuel_entries', sa.Column('odometer', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.alter_column('expenses', 'category',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('expenses', 'receipt_url')
    op.drop_column('expenses', 'date')
    # ### end Alembic commands ###
