"""Add Multi-Tenant company_id fields

Revision ID: d0e3689f73ed
Revises: 12a90941c464
Create Date: 2026-07-18 21:51:31.054317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0e3689f73ed'
down_revision: Union[str, Sequence[str], None] = '12a90941c464'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('slug', sa.String(), nullable=True))
    op.execute("UPDATE companies SET slug = id")
    op.alter_column('companies', 'slug', nullable=False)
    
    op.add_column('companies', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.execute("UPDATE companies SET is_active = true")
    
    op.create_index(op.f('ix_companies_slug'), 'companies', ['slug'], unique=True)
    
    op.add_column('documents', sa.Column('company_id', sa.String(), nullable=True))
    op.execute("UPDATE documents SET company_id = (SELECT id FROM companies LIMIT 1)")
    op.alter_column('documents', 'company_id', nullable=False)
    
    op.create_index(op.f('ix_documents_company_id'), 'documents', ['company_id'], unique=False)
    op.create_foreign_key('fk_documents_company_id', 'documents', 'companies', ['company_id'], ['id'])
    
    op.add_column('expenses', sa.Column('company_id', sa.String(), nullable=True))
    op.execute("UPDATE expenses SET company_id = (SELECT id FROM companies LIMIT 1)")
    op.alter_column('expenses', 'company_id', nullable=False)
    
    op.create_index(op.f('ix_expenses_company_id'), 'expenses', ['company_id'], unique=False)
    op.create_foreign_key('fk_expenses_company_id', 'expenses', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_expenses_company_id', 'expenses', type_='foreignkey')
    op.drop_index(op.f('ix_expenses_company_id'), table_name='expenses')
    op.drop_column('expenses', 'company_id')
    op.drop_constraint('fk_documents_company_id', 'documents', type_='foreignkey')
    op.drop_index(op.f('ix_documents_company_id'), table_name='documents')
    op.drop_column('documents', 'company_id')
    op.drop_index(op.f('ix_companies_slug'), table_name='companies')
    op.drop_column('companies', 'is_active')
    op.drop_column('companies', 'slug')
    # ### end Alembic commands ###
