"""add fuel and other expenses to trip

Revision ID: e3cf4ba1cc9e
Revises: d2db869ae8c9
Create Date: 2026-07-16 14:51:13.031678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3cf4ba1cc9e'
down_revision: Union[str, Sequence[str], None] = 'd2db869ae8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('fuel_cost', sa.Float(), nullable=True))
    op.add_column('trips', sa.Column('other_expenses', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'other_expenses')
    op.drop_column('trips', 'fuel_cost')
    # ### end Alembic commands ###
