"""Phase 3B.3 Driver Portal

Revision ID: fc0f6a718d49
Revises: 1c14bf181c0e
Create Date: 2026-07-16 10:47:17.797776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc0f6a718d49'
down_revision: Union[str, Sequence[str], None] = '1c14bf181c0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fuel_entries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('driver_id', sa.String(), nullable=False),
    sa.Column('trip_id', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('station', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('odometer', sa.Float(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('receipt_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fuel_entries_company_id'), 'fuel_entries', ['company_id'], unique=False)
    op.create_index(op.f('ix_fuel_entries_driver_id'), 'fuel_entries', ['driver_id'], unique=False)
    op.create_index(op.f('ix_fuel_entries_id'), 'fuel_entries', ['id'], unique=False)
    op.create_index(op.f('ix_fuel_entries_trip_id'), 'fuel_entries', ['trip_id'], unique=False)
    op.create_table('trip_activity_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('trip_id', sa.String(), nullable=False),
    sa.Column('driver_id', sa.String(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_activity_logs_company_id'), 'trip_activity_logs', ['company_id'], unique=False)
    op.create_index(op.f('ix_trip_activity_logs_driver_id'), 'trip_activity_logs', ['driver_id'], unique=False)
    op.create_index(op.f('ix_trip_activity_logs_id'), 'trip_activity_logs', ['id'], unique=False)
    op.create_index(op.f('ix_trip_activity_logs_trip_id'), 'trip_activity_logs', ['trip_id'], unique=False)
    op.add_column('drivers', sa.Column('email', sa.String(), nullable=True))
    op.add_column('users', sa.Column('must_change_password', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'must_change_password')
    op.drop_column('drivers', 'email')
    op.drop_index(op.f('ix_trip_activity_logs_trip_id'), table_name='trip_activity_logs')
    op.drop_index(op.f('ix_trip_activity_logs_id'), table_name='trip_activity_logs')
    op.drop_index(op.f('ix_trip_activity_logs_driver_id'), table_name='trip_activity_logs')
    op.drop_index(op.f('ix_trip_activity_logs_company_id'), table_name='trip_activity_logs')
    op.drop_table('trip_activity_logs')
    op.drop_index(op.f('ix_fuel_entries_trip_id'), table_name='fuel_entries')
    op.drop_index(op.f('ix_fuel_entries_id'), table_name='fuel_entries')
    op.drop_index(op.f('ix_fuel_entries_driver_id'), table_name='fuel_entries')
    op.drop_index(op.f('ix_fuel_entries_company_id'), table_name='fuel_entries')
    op.drop_table('fuel_entries')
    # ### end Alembic commands ###
